### ISSUE TITLE
Exp window update

### ISSUE THREAD

**Issue by Joelnh** [vtcifer/g3-standalone-xp#8]
I have a spider from the fest and noticed that the exp window doesn't keep up with what has been drained. 
right now after resting, I type exp and there are 4 skills still above 0 and the exp window shows 17 skills.

maybe it's a feature that is already there, but I have no info on what any of the plugin features do. 
most are easy to figure out but some I am not sure of, and I don't know of any / commands for in genie.

**Comment by vtcifer** [comment]
This is caused by the game not sending an xml exp update when it's used. GMs need to fix it. 

Use exp 0 to clear.

**Comment by Joelnh** [comment]
was just about to close this, found the old genie site with commands that I couldn't locate. 
so I added a /track clear followed by skills and it updates the exp window. but exp 0 is much faster
and very fast reply, kudos. 

http://www.genieclient.com/bulletin/topic/2837-downloadexperience-tracker/
